steps:
  # Build the image
  - id: Build the image
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/analog-grin-419814/nestjs-app/nestjs-app:$SHORT_SHA",
        ".",
      ]
      
  # Scanning the image
  - id: Scan The Image
     name: 'gcr.io/cloud-builders/gcloud'
     entrypoint: /bin/bash
     args:
     - -c
     - |
       gcloud artifacts docker images scan us-central1-docker.pkg.dev/analog-grin-419814/nestjs-app/nestjs-app:$SHORT_SHA \
       --format='value(response.scan)' > /workspace/scan_id.txt

  # Check For Vulnerabilities within the Image
  - id: Check For Vulnerabilities within the Image
     name: 'gcr.io/cloud-builders/gcloud'
     entrypoint: /bin/bash
     args:
     - -c
     - |
       gcloud artifacts docker images list-vulnerabilities $(cat /workspace/scan_id.txt) \
       --format='value(vulnerability.effectiveSeverity)' | if grep -Fxq $_SEVERITY; \
       then echo 'Vulnerability check failed for docker image revision ID "$REVISION_ID", and will not be pushed to Artifact Registry Repo "$_CONTAINER_REPO_NAME" because "$_SEVERITY" checks are impacting the image and needs to be fixed' && exit 1; else exit 0; fi

  # Capturing the image digest
  - id: Capture Image Digest Information
     name: 'gcr.io/cloud-builders/gcloud'
     entrypoint: /bin/bash
     args:
      - -c
      - |
        gcloud container images describe us-central1-docker.pkg.dev/analog-grin-419814/nestjs-app/nestjs-app:$SHORT_SHA \
        --format='get(image_summary.digest)' > /workspace/digest.txt
  
  # Push the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/analog-grin-419814/nestjs-app/nestjs-app:$SHORT_SHA",
      ]

  # Create release in Google Cloud Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "deploy",
        "releases",
        "create",
        "release-$BUILD_ID",
        "--delivery-pipeline",
        "nestjs-app",
        "--region",
        "us-central1",
        "--annotations",
        "release-version=1",
        "--source",
        "./",
        "--images",
        "nestjs-app=us-central1-docker.pkg.dev/analog-grin-419814/nestjs-app/nestjs-app:$SHORT_SHA",
      ]
