apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: nestjs-app
description: Nest.js App Deployment Pipeline
serialPipeline:
  stages:
  - targetId: staging
  - targetId: production
---
  
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: Staging Environment
run:
  location: projects/river-clover-404404/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: Production Environment
run:
  location: projects/river-clover-404404/locations/us-central1
